### ISSUE TITLE
Crash with carpet-fixes

### ISSUE THREAD

**Issue by KosmX** [BlanketMC/blanket-client-tweaks#18]
- Minecraft version 1.18.1
 - Mod version current build
 -  carpet-fixes-1.18.1-1.5.1+v220107

**Minecraft crash report**
https://paste.ee/p/SgkU6

**Comment by FxMorin** [comment]
Should be fixed in the next carpet-fixes update. Since I am removing all client fixes and moving them into blanket

**Comment by FxMorin** [comment]
Should be fixed with the latest release v1.7.0
