### ISSUE TITLE
Doesn't work with Quilt Loader

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [BlanketMC/blanket-client-tweaks#32]
**Describe the bug**
Fabric mods are supposed to work with the Quilt loader, but some do not for various reasons, most commonly relying on certain fabric internals. Quilt officially became beta yesterday, so I am reporting it now.

**To Reproduce**
1. Install the Quilt loader: https://quiltmc.org/install/
2. Download this mod.
3. Install quilt standard libraries. These are basically "quilt api", and bundle a "quilted fabric api" which replaces the normal "fabric api". https://modrinth.com/mod/qsl/versions
4. Try to launch the game
5. Notice that the game crashes on startup.

**Expected behavior**
I expected the mod to launch and work like it does on Fabric.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Minecraft version [1.18.2]
 - Mod version [1.0.2]

**Minecraft crash report**
The game crashes before a crash report is generated. Here is [the log](https://gist.github.com/DragonEggBedrockBreaking/e8ff3308e412b8d44109cc962410f9aa).

**Additional context**
N/A

**Comment by KosmX** [comment]
Some conflict avoidance mechanics in this use FabricLoader to check other mods.  
I'll look at it later today or tomorrow.

**Comment by DragonEggBedrockBreaking** [comment]
For any other Quilt users who are waiting for this to be fixed, [my fork](https://github.com/DragonEggBedrockBreaking/blanket-client-tweaks) provides a temporary solution, by removing the guardian beam fix mixin, and therefore removing the compatibility code that causes the Quilt incompatibility, until a proper solution is implemented in this mod.

**Comment by KosmX** [comment]
# Sorry for being inactive...   

Can you check if this works?
https://kosmx.dev/randomFiles/Blanket%20Client%20tweaks-1.0.2-SNAPSHOT-3828182.jar

**Comment by KosmX** [comment]
The Guardian fix should do **nothing** with this incompatibility, why do you think it is the cause?

**Comment by DragonEggBedrockBreaking** [comment]
> The Guardian fix should do **nothing** with this incompatibility, why do you think it is the cause?

I don't... The cause is clearly the sodium extra compatibility code, but since I use sodium extra, if I remove the sodium extra compatibility code, then I need to remove the guardian fix so that it doesn't crash with sodium extra.

**Comment by DragonEggBedrockBreaking** [comment]
> Sorry for being inactive...
> 
> Can you check if this works? https://kosmx.dev/randomFiles/Blanket%20Client%20tweaks-1.0.2-SNAPSHOT-3828182.jar

This works, thanks!
