### ISSUE TITLE
Blanket Crashing on Pre-launch, unknown compatibility issue

### ISSUE THREAD

**Issue by MaranRoseGIT** [BlanketMC/blanket-client-tweaks#35]
**_Minecraft Fabric 1.18.2_**

Log of Crash: [https://pastebin.com/6KqMAY1q](url)

Completely unsure what is causing this, don't mind the mo'enchant's mixin issue, it's something I am trying to get in contact with the other mod creator to fix.

Edit: It does seem like mo'enchants is causing this but I am unsure how it's suddenly doing so, as this was not an issue in any case before.

**Comment by KosmX** [comment]
https://gitlab.com/biom4st3r/moenchant-lib/-/blob/master/src/main/java/biom4st3r/libs/moenchant_lib/Plugin.java#L43  
It does not look very safe.  
Blanket has to early-initialize a Mixin what is targeting a builtin library.

**Comment by MaranRoseGIT** [comment]
Should I talk to biom4st3r about this issue aswell? I'm attempting to get into contact with him through the fabric discord. If this is more of a bigger issue, I can bring it to their attention asap.

**Comment by KosmX** [comment]
I don't know it yet, it is, just a guess.  
I'll test it soon.

**Comment by KosmX** [comment]
Has this been fixed?
