### ISSUE TITLE
Question About Blanket: Can Blanket cause a false positive on a Multiplayer server depending on the anti-cheat software being used?

### ISSUE THREAD

**Issue by ghost** [BlanketMC/blanket-client-tweaks#38]
Hey! I have a question about blanket, I hope u don't mind!
I've been a bit on edge about this mod if I where to use it on a Multiplayer server. Could it be possible for a false positive to happen and detect something wrongfully?
Please let me know! Thank you! :D

**Comment by KosmX** [comment]
There is no simple answer for your question.  
In Blanket, every tweak/fix is fully configurable, if you disable everything, it should be impossible to detect this mod.  

Rendering and UI fixes can not be monitored by the server, using those shouldn't trigger anti-cheat.  

Maybe the only thing in this mod what might trigger anti-cheat is minecart rotation *tweak*. (disabled by default)  
It makes the player rotate with the minecart, and the server might not like it.

**Comment by ghost** [comment]
Alrighty. thanks man!
