### ISSUE TITLE
Game crashes with modified authlib [ely.by]

### ISSUE THREAD

**Issue by acerola0rion598** [BlanketMC/blanket-client-tweaks#46]
**Describe the bug**
The game crashes on start

**Desktop:**
 - Minecraft version 1.20.1
 - Mod version 1.1.4
 - Fabric API version 0.87.0

**Minecraft crash report**
[crash_report.txt](https://github.com/BlanketMC/blanket-client-tweaks/files/12365243/crash_report.txt)
[latest.log](https://github.com/BlanketMC/blanket-client-tweaks/files/12365247/latest.log)

**Comment by KosmX** [comment]
#44 You're using a modified authlib, blanket tries to modify it more.  
Create a file with the confent.

`.minecraft/config/blanket-client.mixin.properties` :  
```
YggdrasilUserApiService_syncBlockListMixin = false
```
